"""fiesta.tax._js_parity — generate a JS-readable slabs bundle.

The S0 landing estimator runs a slider in the browser and needs to show a
live tax number as the user drags. Calling the server for every drag would
be too slow. Instead, we ship a small JSON bundle that mirrors slabs.yaml,
and the browser implements ONLY the slab walk (the most error-prone bit
stays server-authoritative for S12 / S14).

Server is authoritative:
  - All persisted tax numbers (S12, S14 pre-fill) come from the Python engine.
  - JS preview shows an in-page number that says "preview — final figure
    after sign-up". It is NOT a substitute for the server compute.

This module emits:
  - JSON file (`fiesta/static/js/tax/slabs.json`) — the data bundle
  - JS module (`fiesta/static/js/tax/engine.js`) — the slab walker

Both are generated, not hand-edited. Regenerate after any slabs.yaml change.

CLI:
    python -m fiesta.tax._js_parity --out fiesta/static/js/tax

If called as a function:
    from fiesta.tax._js_parity import generate
    generate(out_dir=Path("fiesta/static/js/tax"))
"""

from __future__ import annotations

import argparse
import json
from decimal import Decimal
from pathlib import Path
from typing import Any

from .brackets import _load_slabs_yaml


_JS_ENGINE_SOURCE = """\
// fiesta/static/js/tax/engine.js
// AUTO-GENERATED by fiesta.tax._js_parity. DO NOT HAND-EDIT.
// Regenerate via `python -m fiesta.tax._js_parity`.
//
// Browser-side slab walker. Mirrors fiesta.tax.brackets.compute_bracket_tax
// AND compute_bracket_tax_dual_track (CEO directive 2026-05-20).
// Slabs data loaded from sibling slabs.json. PREVIEW ONLY — server-side
// fiesta.tax.engine.compute_tax_25_26 is authoritative for all persisted
// values (S12 tax bill, S14 Auto-File pre-fill).
//
// Numbers in JS are 64-bit floats. For LKR amounts well under 2^53 (~9e15)
// the precision is fine for preview math. Cent-accurate persistence happens
// server-side with Python Decimal.

export function loadSlabs() {
  return fetch(new URL("./slabs.json", import.meta.url)).then(r => r.json());
}

function walkSingleTrack(taxable, brackets) {
  let remaining = taxable;
  let prevUpper = 0;
  const byBand = [];
  let marginalRate = brackets[0].rate;
  for (const band of brackets) {
    const bandLower = prevUpper;
    const bandUpper = (band.up_to === null) ? null : band.up_to;
    let incomeInBand;
    if (bandUpper === null) {
      incomeInBand = remaining;
    } else {
      const width = band.up_to - bandLower;
      incomeInBand = Math.min(remaining, width);
      if (incomeInBand < 0) incomeInBand = 0;
    }
    const taxInBand = incomeInBand * band.rate;
    byBand.push({
      band_lower_lkr: bandLower,
      band_upper_lkr: bandUpper,
      income_in_band_lkr: incomeInBand,
      rate: band.rate,
      tax_in_band_lkr: taxInBand,
      track: null,
    });
    if (incomeInBand > 0) marginalRate = band.rate;
    remaining -= incomeInBand;
    if (band.up_to !== null) prevUpper = band.up_to;
    if (remaining < 0) remaining = 0;
  }
  return { byBand, marginalRate };
}

function walkDualTrack(taxable, yearEntry, foreignGross, localGross) {
  // 25/26 dual-track per CEO directive 2026-05-20.
  const firstBand = yearEntry.first_taxable_band;
  const foreignCap = yearEntry.foreign_above_first_band;
  const localBrackets = (yearEntry.local_above_first_band || {}).brackets || [];

  const firstTop = firstBand.up_to;
  const firstRate = firstBand.rate;
  const foreignRate = foreignCap.flat_rate;

  // Step 1: first taxable band (shared).
  const firstFilled = Math.min(Math.max(taxable, 0), firstTop);
  const firstTax = firstFilled * firstRate;
  const byBand = [{
    band_lower_lkr: 0,
    band_upper_lkr: firstTop,
    income_in_band_lkr: firstFilled,
    rate: firstRate,
    tax_in_band_lkr: firstTax,
    track: "first",
  }];

  // Step 2: split above-first-band by source. Conservative default: if
  // both foreign and local gross are zero, treat as 100% local.
  const remaining = Math.max(taxable - firstFilled, 0);
  const totalSrc = foreignGross + localGross;
  const foreignShare = (totalSrc > 0) ? (foreignGross / totalSrc) : 0;
  const foreignAbove = remaining * foreignShare;
  const localAbove = remaining - foreignAbove;

  // Step 3: foreign band (flat cap).
  const foreignTax = foreignAbove * foreignRate;
  byBand.push({
    band_lower_lkr: firstTop,
    band_upper_lkr: null,
    income_in_band_lkr: foreignAbove,
    rate: foreignRate,
    tax_in_band_lkr: foreignTax,
    track: "foreign",
  });

  // Step 4: local progressive walk.
  let marginalRate = (foreignAbove > 0) ? foreignRate : firstRate;
  let localRemaining = localAbove;
  let prevRel = 0;
  for (const band of localBrackets) {
    const upTo = band.up_to;
    const rate = band.rate;
    const bandLowerAbs = firstTop + prevRel;
    let bandUpperAbs, incomeInBand;
    if (upTo === null) {
      bandUpperAbs = null;
      incomeInBand = Math.max(localRemaining, 0);
    } else {
      const bandTopRel = upTo;
      bandUpperAbs = firstTop + bandTopRel;
      const width = bandTopRel - prevRel;
      incomeInBand = Math.min(Math.max(localRemaining, 0), width);
    }
    const taxInBand = incomeInBand * rate;
    byBand.push({
      band_lower_lkr: bandLowerAbs,
      band_upper_lkr: bandUpperAbs,
      income_in_band_lkr: incomeInBand,
      rate: rate,
      tax_in_band_lkr: taxInBand,
      track: "local",
    });
    if (incomeInBand > 0) marginalRate = rate;
    localRemaining -= incomeInBand;
    if (upTo !== null) prevRel = upTo;
  }

  return { byBand, marginalRate };
}

export function computeTax(grossIncomeLkr, deductionsLkr, year, slabsBundle, options) {
  options = options || {};
  const seniorCitizen = !!options.seniorCitizen;
  const yearEntry = slabsBundle.years[year];
  if (!yearEntry) throw new Error("Tax year not in slabs bundle: " + year);

  const personalRelief = yearEntry.personal_relief_lkr;
  const seniorExtra = seniorCitizen ? (yearEntry.senior_citizen_extra_relief_lkr || 0) : 0;
  const solarCap = 600000;
  const solarReliefApplied = Math.min(deductionsLkr.solar_lkr || 0, solarCap);
  const rentRelief = deductionsLkr.rent_lkr || 0;
  const expenditureRelief = deductionsLkr.expenditure_lkr || 0;

  const totalRelief = personalRelief + seniorExtra + solarReliefApplied + rentRelief + expenditureRelief;
  const taxable = Math.max(0, grossIncomeLkr - totalRelief);

  // Dispatch on structure.
  let byBand, marginalRate;
  if (yearEntry.structure === "dual_track") {
    // Caller may pass options.foreignGross + options.localGross for the
    // source split. If not provided, default to 100% local (conservative).
    const foreignGross = +(options.foreignGross || 0);
    const localGross = +((options.localGross !== undefined) ? options.localGross : grossIncomeLkr);
    const out = walkDualTrack(taxable, yearEntry, foreignGross, localGross);
    byBand = out.byBand;
    marginalRate = out.marginalRate;
  } else {
    const out = walkSingleTrack(taxable, yearEntry.brackets);
    byBand = out.byBand;
    marginalRate = out.marginalRate;
  }
  const grossTax = byBand.reduce((s, b) => s + b.tax_in_band_lkr, 0);

  return {
    tax_year: year,
    gross_income_lkr: grossIncomeLkr,
    taxable_income_lkr: taxable,
    relief_applied_lkr: totalRelief,
    by_band: byBand,
    gross_tax_lkr: grossTax,
    net_tax_due_lkr: grossTax,
    marginal_rate: marginalRate,
    effective_rate: grossIncomeLkr > 0 ? (grossTax / grossIncomeLkr) : 0,
  };
}
"""


def _convert_for_json(obj: Any) -> Any:
    """Recursively convert Decimal -> float (for JS consumption)."""
    if isinstance(obj, Decimal):
        return float(obj)
    if isinstance(obj, dict):
        return {k: _convert_for_json(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_convert_for_json(v) for v in obj]
    return obj


def build_slabs_bundle() -> dict:
    """Read slabs.yaml and return a JS-friendly dict (no Decimal, no None
    keys, normalised shape).

    Supports both single-track and dual-track year shapes; passes them
    through with the `structure` discriminator so the JS engine can dispatch.
    """
    data = _load_slabs_yaml()
    out_years = {}
    for year_key, entry in data["years"].items():
        structure = entry.get("structure", "single_track")
        out = {
            "structure": structure,
            "personal_relief_lkr": int(entry.get("personal_relief_lkr", 0)),
            "senior_citizen_extra_relief_lkr": int(
                entry.get("senior_citizen_extra_relief_lkr", 0)
            ),
        }
        if structure == "dual_track":
            first_band = entry.get("first_taxable_band") or {}
            foreign = entry.get("foreign_above_first_band") or {}
            local_block = entry.get("local_above_first_band") or {}
            out["first_taxable_band"] = {
                "up_to": int(first_band.get("up_to", 0)),
                "rate": float(first_band.get("rate", 0)),
            }
            out["foreign_above_first_band"] = {
                "flat_rate": float(foreign.get("flat_rate", 0)),
            }
            out["local_above_first_band"] = {
                "brackets": [
                    {"up_to": b.get("up_to"), "rate": float(b["rate"])}
                    for b in local_block.get("brackets", [])
                ],
            }
        else:
            out["brackets"] = [
                {"up_to": b.get("up_to"), "rate": float(b["rate"])}
                for b in entry.get("brackets", [])
            ]
        out_years[year_key] = out
    return {
        "_format": "fiesta_tax_slabs_v2",  # bumped: now supports dual-track
        "_generated_by": "fiesta.tax._js_parity",
        "years": out_years,
    }


def generate(out_dir: Path) -> tuple[Path, Path]:
    """Write slabs.json + engine.js to out_dir.

    Returns:
        (slabs_path, engine_path)
    """
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    slabs_path = out_dir / "slabs.json"
    engine_path = out_dir / "engine.js"

    bundle = build_slabs_bundle()
    slabs_path.write_text(json.dumps(bundle, indent=2) + "\n", encoding="utf-8")
    engine_path.write_text(_JS_ENGINE_SOURCE, encoding="utf-8")

    return (slabs_path, engine_path)


def _cli() -> None:
    parser = argparse.ArgumentParser(description="Generate JS parity bundle.")
    parser.add_argument(
        "--out",
        default="static/js/tax",
        help="Output directory (relative to repo root or absolute).",
    )
    args = parser.parse_args()
    slabs_path, engine_path = generate(Path(args.out))
    print(f"Wrote: {slabs_path}")
    print(f"Wrote: {engine_path}")


if __name__ == "__main__":
    _cli()


__all__ = ["build_slabs_bundle", "generate"]
